language: node_js
node_js:
  - "6"
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - node ./node_modules/.bin/knex migrate:latest --knexfile=./database/config/knexfile.js
  - cp ./config-travis.js ./config.js